// Login
export const LOGIN_REQUEST: string = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS: string = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE: string = 'LOGIN_FAILURE';

// Sign Up
export const SIGNUP_REQUEST: string = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS: string = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE: string = 'SIGNUP_FAILURE';

// Sign Up Confirmation
export const SIGNUP_CONFIRMATION_REQUIRED: string = 'SIGNUP_CONFIRMATION_REQUIRED';
export const SIGNUP_CONFIRMATION_REQUEST: string = 'SIGNUP_CONFIRMATION_REQUEST';
export const SIGNUP_CONFIRMATION_SUCCESS: string = 'SIGNUP_CONFIRMATION_SUCCESS';
export const SIGNUP_CONFIRMATION_FAILURE: string = 'SIGNUP_CONFIRMATION_FAILURE';

// User Profile
export const USER_PROFILE_SUB_REQUEST: string = 'USER_PROFILE_SUB_REQUEST';
export const USER_PROFILE_SUB_RECEIVED: string = 'USER_PROFILE_SUB_RECEIVED';
export const USER_PROFILE_SUB_FAILURE: string = 'USER_PROFILE_SUB_FAILURE';
export const USER_PROFILE_UNSUB: string = 'USER_PROFILE_UNSUB';
export const UPLOAD_AVATAR_REQUEST: string = 'UPLOAD_AVATAR_REQUEST';
export const UPLOAD_AVATAR_SUCCESS: string = 'UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_FAILURE: string = 'UPLOAD_AVATAR_FAILURE';

// Driver Applications
export const DRIVER_APPLICATION_REQUEST: string = 'DRIVER_APPLICATION_REQUEST';
export const DRIVER_APPLICATION_SUCCESS: string = 'DRIVER_APPLICATION_SUCCESS';
export const DRIVER_APPLICATION_FAILURE: string = 'DRIVER_APPLICATION_FAILURE';

// Update User
export const UPDATE_USER_REQUEST: string = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS: string = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE: string = 'UPDATE_USER_FAILURE';

// Update Password
export const UPDATE_PASSWORD_REQUEST: string = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS: string = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE: string = 'UPDATE_PASSWORD_FAILURE';

// Update Email
export const UPDATE_EMAIL_REQUEST: string = 'UPDATE_EMAIL_REQUEST';
export const UPDATE_EMAIL_SUCCESS: string = 'UPDATE_EMAIL_SUCCESS';
export const UPDATE_EMAIL_FAILURE: string = 'UPDATE_EMAIL_FAILURE';

// Journeys
export const JOURNEYS_REQUEST: string = 'JOURNEYS_REQUEST';
export const JOURNEYS_SUCCESS: string = 'JOURNEYS_SUCCESS';
export const JOURNEYS_FAILURE: string = 'JOURNEYS_FAILURE';

// Cancel Passenger Accepted Journeys
export const CANCEL_PASSENGER_JOURNEY_REQUEST: string = 'CANCEL_PASSENGER_JOURNEY_REQUEST';
export const CANCEL_PASSENGER_JOURNEY_SUCCESS: string = 'CANCEL_PASSENGER_JOURNEY_SUCCESS';
export const CANCEL_PASSENGER_JOURNEY_FAILURE: string = 'CANCEL_PASSENGER_JOURNEY_FAILURE';

// Driver Journey
export const JOURNEY_DETAILS_REQUEST: string = 'JOURNEY_DETAILS_REQUEST';
export const JOURNEY_DETAILS_SUCCESS: string = 'JOURNEY_DETAILS_SUCCESS';
export const JOURNEY_DETAILS_FAILURE: string = 'JOURNEY_DETAILS_FAILURE';

// Passenger Journey
export const PASSENGER_JOURNEY_DETAILS_REQUEST: string = 'PASSENGER_JOURNEY_DETAILS_REQUEST';
export const PASSENGER_JOURNEY_DETAILS_SUCCESS: string = 'PASSENGER_JOURNEY_DETAILS_SUCCESS';
export const PASSENGER_JOURNEY_DETAILS_FAILURE: string = 'PASSENGER_JOURNEY_DETAILS_FAILURE';
export const UPDATE_DRIVER_LOCATION: string = 'UPDATE_DRIVER_LOCATION';

// Start Journey
export const START_JOURNEY_REQUEST: string = 'START_JOURNEY_REQUEST';
export const START_JOURNEY_SUCCESS: string = 'START_JOURNEY_SUCCESS';
export const START_JOURNEY_FAILURE: string = 'START_JOURNEY_FAILURE';

// End Journey
export const END_JOURNEY_REQUEST: string = 'END_JOURNEY_REQUEST';
export const END_JOURNEY_SUCCESS: string = 'END_JOURNEY_SUCCESS';
export const END_JOURNEY_FAILURE: string = 'END_JOURNEY_FAILURE';

// Driver Movement
export const DRIVER_MOVEMENT_REQUEST: string = 'DRIVER_MOVEMENT_REQUEST';
export const DRIVER_MOVEMENT_SUCCESS: string = 'DRIVER_MOVEMENT_SUCCESS';
export const DRIVER_MOVEMENT_FAILURE: string = 'DRIVER_MOVEMENT_FAILURE';

// Google Places Search
export const GOOGLE_PLACES_SEARCH_REQUEST: string = 'GOOGLE_PLACES_SEARCH_REQUEST';
export const GOOGLE_PLACES_SEARCH_SUCCESS: string = 'GOOGLE_PLACES_SEARCH_SUCCESS';
export const GOOGLE_PLACES_SEARCH_FAILURE: string = 'GOOGLE_PLACES_SEARCH_FAILURE';
export const GOOGLE_PLACES_SEARCH_CLEAR_RESULTS: string = 'GOOGLE_PLACES_SEARCH_CLEAR_RESULTS';
export const SELECT_GOOGLE_PLACE: string = 'SELECT_GOOGLE_PLACE';

// Google Places Details
export const GOOGLE_PLACES_DETAILS_REQUEST: string = 'GOOGLE_PLACES_DETAILS_REQUEST';
export const GOOGLE_PLACES_DETAILS_SUCCESS: string = 'GOOGLE_PLACES_DETAILS_SUCCESS';
export const GOOGLE_PLACES_DETAILS_FAILURE: string = 'GOOGLE_PLACES_DETAILS_FAILURE';

// Create Journey
export const CREATE_JOURNEY_REQUEST: string = 'CREATE_JOURNEY_REQUEST';
export const CREATE_JOURNEY_SUCCESS: string = 'CREATE_JOURNEY_SUCCESS';
export const CREATE_JOURNEY_FAILURE: string = 'CREATE_JOURNEY_FAILURE';
