// Login
export const LOGIN_REQUEST: string = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS: string = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE: string = 'LOGIN_FAILURE';

// Sign Up
export const SIGNUP_REQUEST: string = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS: string = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE: string = 'SIGNUP_FAILURE';

// Sign Up Confirmation
export const SIGNUP_CONFIRMATION_REQUIRED: string = 'SIGNUP_CONFIRMATION_REQUIRED';
export const SIGNUP_CONFIRMATION_REQUEST: string = 'SIGNUP_CONFIRMATION_REQUEST';
export const SIGNUP_CONFIRMATION_SUCCESS: string = 'SIGNUP_CONFIRMATION_SUCCESS';
export const SIGNUP_CONFIRMATION_FAILURE: string = 'SIGNUP_CONFIRMATION_FAILURE';

// Driver Applications
export const DRIVER_APPLICATION_REQUEST: string = 'DRIVER_APPLICATION_REQUEST';
export const DRIVER_APPLICATION_SUCCESS: string = 'DRIVER_APPLICATION_SUCCESS';
export const DRIVER_APPLICATION_FAILURE: string = 'DRIVER_APPLICATION_FAILURE';

// Admin Driver Applications (WebSockets Demo)
export const STORE_APPLICATIONS: string = 'STORE_APPLICATIONS';

// User Profile
export const USER_PROFILE_SUB_REQUEST: string = 'USER_PROFILE_SUB_REQUEST';
export const USER_PROFILE_SUB_RECEIVED: string = 'USER_PROFILE_SUB_RECEIVED';
export const USER_PROFILE_SUB_FAILURE: string = 'USER_PROFILE_SUB_FAILURE';
export const USER_PROFILE_UNSUB: string = 'USER_PROFILE_UNSUB';
export const UPLOAD_AVATAR_REQUEST: string = 'UPLOAD_AVATAR_REQUEST';
export const UPLOAD_AVATAR_SUCCESS: string = 'UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_FAILURE: string = 'UPLOAD_AVATAR_FAILURE';

// Update User
export const UPDATE_USER_REQUEST: string = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS: string = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE: string = 'UPDATE_USER_FAILURE';

// Update Password
export const UPDATE_PASSWORD_REQUEST: string = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS: string = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE: string = 'UPDATE_PASSWORD_FAILURE';

// Update Email
export const UPDATE_EMAIL_REQUEST: string = 'UPDATE_EMAIL_REQUEST';
export const UPDATE_EMAIL_SUCCESS: string = 'UPDATE_EMAIL_SUCCESS';
export const UPDATE_EMAIL_FAILURE: string = 'UPDATE_EMAIL_FAILURE';

// Driver Journeys
export const DRIVER_JOURNEYS_REQUEST: string = 'DRIVER_JOURNEYS_REQUEST';
export const DRIVER_JOURNEYS_SUCCESS: string = 'DRIVER_JOURNEYS_SUCCESS';
export const DRIVER_JOURNEYS_FAILURE: string = 'DRIVER_JOURNEYS_FAILURE';

// Journey
export const JOURNEY_DETAILS_REQUEST: string = 'JOURNEY_DETAILS_REQUEST';
export const JOURNEY_DETAILS_SUCCESS: string = 'JOURNEY_DETAILS_SUCCESS';
export const JOURNEY_DETAILS_FAILURE: string = 'JOURNEY_DETAILS_FAILURE';

// Start Journey
export const START_JOURNEY_REQUEST: string = 'START_JOURNEY_REQUEST';
export const START_JOURNEY_SUCCESS: string = 'START_JOURNEY_SUCCESS';
export const START_JOURNEY_FAILURE: string = 'START_JOURNEY_FAILURE';

// End Journey
export const END_JOURNEY_REQUEST: string = 'END_JOURNEY_REQUEST';
export const END_JOURNEY_SUCCESS: string = 'END_JOURNEY_SUCCESS';
export const END_JOURNEY_FAILURE: string = 'END_JOURNEY_FAILURE';
