# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project300' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project300

  pod 'GoogleMaps'

  target 'Project300-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Project300Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
